
export class Plant {
  constructor(
    id,
    nombre,
    descripcion,
    categoria,
    img,
    riego,
    luz,
    uso,
    beneficios,
    comoPlantar
  ) {
    this.id = id;
    this.nombre = nombre;
    this.descripcion = descripcion;
    this.categoria = categoria;
    this.img = img;
    this.riego = riego;
    this.luz = luz;
    this.uso = uso;
    this.beneficios = beneficios;
    this.comoPlantar = comoPlantar;
  }

  static getRecomendations(plantas) {
    return plantas.filter((plant) => plant.categoria.includes("Facil"));
  }

  static getHuerto(plantas) {
    return plantas.filter((plant) => plant.categoria.includes("Comestible"));
  }
}
 export const plantas = [
   new Plant(
     1,
     "Tomate",
     "Fruto comestible muy popular y versátil en la cocina, rico en licopeno y antioxidantes.",
     ["Comestible", "Medicinal"],
     "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvw7SVlbhkUYpRVK_f4LZFxVwAdT4hZ4YhMw&s",
     "Riego regular, manteniendo el sustrato húmedo sin encharcar. Evitar mojar las hojas.",
     "Sol directo (mínimo 6 horas diarias).",
     "Crudo en ensaladas, cocinado en salsas, guisos o como base de conservas.",
     "Rico en vitamina C, antioxidante, beneficioso para la piel y sistema inmune.",
     [
       "Temporada: Primavera.",
       "Tiempo hasta recolección: 3-4 meses.",
       "Suelo/Maceta: Suelo fértil, bien drenado, abono regular.",
       "Regado: Riego regular, evitando encharcar.",
       "Consejos adicionales: Requiere tutorado.",
     ]
   ),
   new Plant(
     2,
     "Menta",
     "Planta aromática con propiedades digestivas y refrescantes, ideal para infusiones y repelente natural.",
     ["Comestible", "Antimosquitos", "Medicinal"],
     "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJNv3zoihZom2jLKJ6JCnMv2HM6qG41dhVkA&s",
     "Riego frecuente, especialmente en épocas calurosas. Evitar que el sustrato se seque.",
     "Sombra parcial o luz indirecta.",
     "Infusión digestiva, hojas frescas en ensaladas o mojitos.",
     "Alivia trastornos digestivos, mejora la respiración y repele mosquitos.",
     [
       "Temporada: Primavera.",
       "Tiempo hasta recolección: 2-3 meses.",
       "Suelo/Maceta: Prefiere maceta debido a su crecimiento invasivo.",
       "Regado: Mantener humedad constante.",
       "Consejos adicionales: Evitar la exposición al sol directo durante el calor extremo.",
     ]
   ),
   new Plant(
     3,
     "Albahaca",
     "Hierba aromática esencial en la cocina mediterránea, también actúa como repelente natural.",
     ["Comestible", "Antimosquitos"],
     "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSbsQrhOqn9pluPyRev1EqaPaKSFXBdi6cUlA&s",
     "Riego regular, evitando encharcamientos.",
     "Sol directo o semisombra.",
     "Ideal para pesto, ensaladas, pizzas o infusiones relajantes.",
     "Propiedades antiinflamatorias, antibacterianas y repelente de insectos.",
     [
       "Temporada: Finales de primavera.",
       "Tiempo hasta recolección: 2-3 meses.",
       "Suelo/Maceta: Suelo fértil, bien drenado.",
       "Regado: Riego regular, evitando que se encharque el suelo.",
       "Consejos adicionales: Sensible al frío, poda regular para estimular el crecimiento.",
     ]
   ),
   new Plant(
     4,
     "Romero",
     "Aromática muy resistente que mejora la memoria, la circulación y es excelente en guisos.",
     ["Comestible", "Medicinal", "Facil"],
     "https://live.staticflickr.com/2250/2457111340_f176fbdf28_b.jpg",
     "Riego escaso. Tolera la sequía.",
     "Sol directo.",
     "Uso en carnes, pan aromatizado o infusiones.",
     "Estimula la memoria y concentración, digestivo, antiséptico.",
     [
       "Temporada: Primavera.",
       "Tiempo hasta recolección: 3-4 meses.",
       "Suelo/Maceta: Suelo seco, bien drenado.",
       "Regado: Riego escaso.",
       "Consejos adicionales: Tolera la sequía, ideal para lugares cálidos.",
     ]
   ),
   new Plant(
     5,
     "Lavanda",
     "Flor aromática usada en relajación, infusiones, y como repelente natural.",
     ["Medicinal", "Antimosquitos", "Facil"],
     "https://live.staticflickr.com/284/31546637321_8477e00641_b.jpg",
     "Riego moderado. Dejar secar el suelo entre riegos.",
     "Sol directo.",
     "En infusión para dormir o en bolsitas aromáticas.",
     "Relajante, alivia ansiedad y repele insectos.",
     [
       "Temporada: Primavera.",
       "Tiempo hasta recolección: 3-4 meses.",
       "Suelo/Maceta: Suelo seco y bien drenado.",
       "Regado: Riego moderado, dejar secar el suelo entre riegos.",
       "Consejos adicionales: Resiste bien el calor.",
     ]
   ),
   new Plant(
     6,
     "Aloe Vera",
     "Planta suculenta con gran valor medicinal para piel, quemaduras y digestión.",
     ["Medicinal", "Facil"],
     "https://live.staticflickr.com/1932/45141727951_2c2be7b348_b.jpg",
     "Riego muy escaso. Dejar secar completamente entre riegos.",
     "Luz abundante, incluso sol directo.",
     "Gel para quemaduras, cortes, acné o batidos.",
     "Cicatrizante, hidratante, digestivo natural.",
     [
       "Temporada: Todo el año.",
       "Tiempo hasta recolección: 1-2 años para una planta madura.",
       "Suelo/Maceta: Suelo arenoso y bien drenado.",
       "Regado: Riego muy escaso, dejar secar entre riegos.",
       "Consejos adicionales: No tolera heladas.",
     ]
   ),
   new Plant(
     7,
     "Hierbabuena",
     "Planta muy similar a la menta, con aroma intenso, útil en cocina y salud digestiva.",
     ["Comestible", "Medicinal"],
     "https://live.staticflickr.com/3805/13924128123_34181c213a_b.jpg",
     "Riego frecuente, mantener el sustrato húmedo.",
     "Luz indirecta o sombra parcial.",
     "Usos culinarios similares a la menta, también en infusiones.",
     "Favorece digestión, alivia dolores estomacales y resfriados.",
     [
       "Temporada: Primavera.",
       "Tiempo hasta recolección: 2-3 meses.",
       "Suelo/Maceta: Suelo húmedo y bien drenado.",
       "Regado: Mantener sustrato húmedo.",
       "Consejos adicionales: Requiere poda regular para controlar su expansión.",
     ]
   ),
   new Plant(
     8,
     "Caléndula",
     "Flor comestible y medicinal, con propiedades antiinflamatorias y uso cosmético.",
     ["Medicinal", "Comestible"],
     "https://imgproxy.infoflora.ch/dmoFt5agqxH8ID0xbrL3bA/rs:fill:400:400:1/g:sm/aHR0cHM6Ly93d3cuaW5mb2Zsb3JhLmNoL2VuLy9hc3NldHMvZGJfZG9jL3NwZWNpZXMvdGF4YV9pbWFnZXMvMjAxNy8wOS8yOC8yMDE3MDkyODEwMjIzOC0yN2RkOTZhYS5qcGc.jpg",
     "Riego moderado. No dejar secar completamente.",
     "Sol directo o semisombra.",
     "En infusión o pétalos en ensaladas.",
     "Regeneradora de piel, ideal para cremas, pomadas o infusión antiinflamatoria.",
     [
       "Temporada: Primavera a verano.",
       "Tiempo hasta recolección: 2-3 meses.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Moderado, evitando el encharcamiento.",
       "Consejos adicionales: Florece gran parte del año.",
     ]
   ),
   new Plant(
     9,
     "Capuchina",
     "Planta ornamental y comestible, con propiedades antibacterianas.",
     ["Comestible", "Medicinal", "Decorativa"],
     "https://live.staticflickr.com/7438/28115760315_fe401073b9_b.jpg",
     "Riego moderado. Evitar exceso de agua.",
     "Sol directo o semisombra.",
     "Flores y hojas en ensaladas o infusiones.",
     "Antibiótica natural, fortalece defensas.",
     [
       "Temporada: Primavera a verano.",
       "Tiempo hasta recolección: 2-3 meses.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Moderado.",
       "Consejos adicionales: Ideal para macetas o bordes.",
     ]
   ),
   new Plant(
     10,
     "Cilantro",
     "Hierba esencial en cocinas del mundo, digestiva y rica en antioxidantes.",
     ["Comestible", "Medicinal"],
     "https://live.staticflickr.com/1561/24311764256_fecb53865d_b.jpg",
     "Riego frecuente. No dejar secar el sustrato.",
     "Sol directo o semisombra.",
     "Ideal para salsas, guisos o ensaladas.",
     "Ayuda en la digestión, detoxifica el cuerpo.",
     [
       "Temporada: Primavera.",
       "Tiempo hasta recolección: 2 meses.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Mantener sustrato húmedo.",
       "Consejos adicionales: Requiere temperaturas moderadas.",
     ]
   ),
   new Plant(
     11,
     "Espinaca",
     "Hortaliza de hoja verde rica en hierro, ideal para ensaladas y batidos.",
     ["Comestible", "Medicinal"],
     "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPcfq6d_u_A71z2bVic7qsAtv6r83lJoxxrw&s",
     "Riego regular, mantener el sustrato húmedo.",
     "Sombra parcial o sol directo.",
     "En ensaladas, cocida o en batidos verdes.",
     "Rica en hierro, vitamina A y C, beneficiosa para la vista y la salud ósea.",
     [
       "Temporada: Otoño a primavera.",
       "Tiempo hasta recolección: 1-2 meses.",
       "Suelo/Maceta: Suelo rico en nutrientes.",
       "Regado: Riego regular.",
       "Consejos adicionales: Requiere temperaturas frescas.",
     ]
   ),
   new Plant(
     12,
     "Ajo",
     "Bulbo con fuerte aroma y potentes beneficios antibacterianos y cardiovasculares.",
     ["Comestible", "Medicinal"],
     "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_UAHFJfwepLdRkLQt9GNI9w2GkZtGQZYvmw&s",
     "Riego moderado hasta que el tallo empiece a secar.",
     "Sol directo.",
     "Cocinado en casi cualquier receta o crudo con aceite.",
     "Antibiótico natural, reduce colesterol, fortalece sistema inmune.",
     "Plantar en otoño. Requiere 6-8 meses hasta cosecha.",
     [
       "Temporada: Otoño a primavera.",
       "Tiempo hasta recolección: 1-2 meses.",
       "Suelo/Maceta: Suelo rico en nutrientes.",
       "Regado: Riego regular.",
       "Consejos adicionales: Requiere temperaturas frescas.",
     ]
   ),
   new Plant(
     13,
     "Cebollino",
     "Aromática tipo cebolla suave, excelente en crudo y muy fácil de cultivar.",
     ["Comestible", "Medicinal"],
     "https://www.5aldia.es/es/wp-content/uploads/2017/09/ha9g.jpg",
     "Riego frecuente sin encharcar.",
     "Luz solar directa o parcial.",
     "En tortilla, crema agria, pan o sopas.",
     "Fuente de vitamina A y C, digestivo.",
     "Crece rápido. Se puede cortar varias veces al año.",
     [
       "Temporada: Primavera a verano.",
       "Tiempo hasta recolección: 1-2 meses.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego frecuente.",
       "Consejos adicionales: Cortar las hojas para promover el crecimiento.",
     ]
   ),
   new Plant(
     14,
     "Citronela",
     "Hierba tropical con fuerte aroma a limón, ideal como antimosquitos natural.",
     ["Antimosquitos", "Medicinal"],
     "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Citronella_mucronata_%28R._et_P.%29_D._Don_%28pabloendemico%29.jpg/500px-Citronella_mucronata_%28R._et_P.%29_D._Don_%28pabloendemico%29.jpg",
     "Riego abundante pero espaciado. Sustrato húmedo.",
     "Sol directo o semisombra.",
     "En infusiones o macerada como repelente.",
     "Ahuyenta mosquitos eficazmente, reduce ansiedad.",
     "Plantar en clima cálido. Requiere espacio y sol.",
     [
       "Temporada: Primavera a verano.",
       "Tiempo hasta recolección: 2-3 meses.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego regular, mantener el suelo húmedo.",
       "Consejos adicionales: Crece mejor en espacios amplios.",
     ]
   ),
   new Plant(
     15,
     "Salvia Elegans",
     "Aromática con propiedades antiinflamatorias y culinarias.",
     ["Comestible", "Medicinal", "Facil"],
     "https://cdn0.ecologiaverde.com/es/posts/3/4/2/salvia_elegans_3243_4_600.webp",
     "Riego moderado. Dejar secar entre riegos.",
     "Sol directo.",
     "En infusiones, guisos y platos de carne.",
     "Reduce inflamaciones, regula la menstruación, antioxidante, beneficiosa para piel y cabello",
     "Plantar en primavera. Poda regular. Tolera sequía.",
     [
       "Temporada: Primavera a otoño.",
       "Tiempo hasta recolección: 2-3 meses.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego moderado.",
       "Consejos adicionales: Poda regularmente para estimular el crecimiento.",
     ]
   ),
   new Plant(
     16,
     "Melisa",
     "También conocida como toronjil, es una planta aromática calmante usada en infusiones relajantes.",
     ["Medicinal"],
     "https://www.spicegarden.eu/WebRoot/StoreLES/Shops/62431129/4BE7/A818/093A/D991/C7B2/C0A8/29BB/894B/Melisse.JPG",
     "Riego frecuente, mantener el sustrato húmedo.",
     "Sombra parcial o luz indirecta.",
     "En infusiones para calmar ansiedad o problemas de sueño.",
     "Relajante natural, alivia estrés y trastornos digestivos.",
     "Plantar en primavera. Crece bien en maceta. Poda regular para estimular crecimiento.",
     [
       "Temporada: Primavera a verano.",
       "Tiempo hasta recolección: 1-2 meses.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego regular.",
       "Consejos adicionales: Crece bien en macetas pequeñas.",
     ]
   ),
   new Plant(
     17,
     "Ortiga",
     "Planta silvestre rica en nutrientes con usos medicinales y culinarios.",
     ["Comestible", "Medicinal"],
     "https://www.lagradaonline.com/actualidad/wp-content/uploads/2025/02/la-planta-de-ortiga-tiene-muchos-beneficios-1.jpg",
     "Riego moderado. Prefiere suelos húmedos.",
     "Sombra parcial.",
     "Cocinada como espinacas, en sopas o infusiones.",
     "Depurativa, rica en hierro, buena para el cabello y la piel.",
     "Recolectar con guantes. Brotes tiernos en primavera son comestibles.",
     [
       "Temporada: Primavera a verano.",
       "Tiempo hasta recolección: 1-2 meses.",
       "Suelo/Maceta: Suelo rico en nutrientes.",
       "Regado: Riego regular.",
       "Consejos adicionales: Usar guantes al recolectar.",
     ]
   ),
   new Plant(
     18,
     "Manzanilla",
     "Planta medicinal usada comúnmente para infusiones relajantes y digestivas.",
     ["Medicinal"],
     "https://bs.plantnet.org/image/o/9e00d061b7d5dcc4a47f8ae536364c75ee156e07",
     "Riego moderado, evitar encharcamientos.",
     "Sol directo.",
     "Infusión calmante para estrés y dolores estomacales.",
     "Antiinflamatoria, calmante, alivia cólicos.",
     "Siembra en primavera. Requiere sol y buena ventilación.",
     [
       "Temporada: Primavera a verano.",
       "Tiempo hasta recolección: 1-2 meses.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego moderado.",
       "Consejos adicionales: Evitar encharcamientos.",
     ]
   ),
   new Plant(
     19,
     "Valeriana",
     "Conocida por sus efectos sedantes, ideal para trastornos del sueño y ansiedad.",
     ["Medicinal"],
     "https://tyt.lt/_data/i/upload/2010/01/30/20100130232501-cc1d2f0d-me.jpg",
     "Riego regular, suelo húmedo pero bien drenado.",
     "Semisombra.",
     "En cápsulas o infusión de la raíz seca.",
     "Sedante natural, combate insomnio y ansiedad.",
     "Plantar en otoño o primavera. Recolectar raíz tras 2 años.",
     [
       "Temporada: Primavera a otoño.",
       "Tiempo hasta recolección: 2-3 años.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego regular.",
       "Consejos adicionales: Recolectar la raíz después de 2 años.",
     ]
   ),
   new Plant(
     20,
     "Eneldo",
     "Hierba aromática usada en cocina y con propiedades digestivas.",
     ["Comestible", "Medicinal"],
     "https://live.staticflickr.com/7823/45809612934_e7b386ae36_b.jpg",
     "Riego regular, especialmente en climas cálidos.",
     "Sol directo.",
     "En pescados, encurtidos y salsas.",
     "Digestivo, alivia flatulencias y cólicos.",
     "Siembra directa. No trasplantar. Ciclo rápido.",
     [
       "Temporada: Primavera a verano.",
       "Tiempo hasta recolección: 1-2 meses.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego regular.",
       "Consejos adicionales: Siembra directa.",
     ]
   ),

   new Plant(
     21,
     "Milenrama",
     "Planta silvestre con propiedades cicatrizantes y reguladoras.",
     ["Medicinal"],
     "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnyfMFbW3wzRZf_glCN1Wca8oABBzklr1TQA&s",
     "Riego escaso. Tolera suelos pobres.",
     "Sol directo.",
     "Infusión para regular el ciclo menstrual.",
     "Antiinflamatoria, cicatrizante, reguladora hormonal.",
     "Plantar en primavera. Muy resistente. Atrae polinizadores.",
     [
       "Temporada: Primavera a otoño.",
       "Tiempo hasta recolección: 2-3 años.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego escaso.",
       "Consejos adicionales: Recolectar la raíz después de 2 años.",
     ]
   ),
   new Plant(
     22,
     "Hisopo",
     "Aromática tradicional usada en infusiones y para aliviar problemas respiratorios.",
     ["Medicinal"],
     "https://cdn.pixabay.com/photo/2016/09/06/23/00/hyssop-1649531_960_720.jpg",
     "Riego moderado. No encharcar.",
     "Sol directo.",
     "Infusión expectorante o como tónico.",
     "Expectorante, antiséptico y digestivo.",
     "Plantar en primavera. Atrayente de abejas.",
     [
       "Temporada: Primavera a verano.",
       "Tiempo hasta recolección: 1 año.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego moderado.",
       "Consejos adicionales: Recoger las hojas antes de la floración.",
     ]
   ),
   new Plant(
     23,
     "Hinojo",
     "Aromática con sabor anisado, usada en cocina y digestiva.",
     ["Comestible", "Medicinal"],
     "https://cdn.pixabay.com/photo/2020/06/08/06/35/fennel-5273536_960_720.jpg",
     "Riego moderado y constante.",
     "Sol directo.",
     "Tallos y semillas en guisos, ensaladas e infusiones.",
     "Digestivo, calma gases y estimula el apetito.",
     "Siembra directa. Requiere espacio y sol.",
     [
       "Temporada: Primavera a otoño.",
       "Tiempo hasta recolección: 2 años.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego moderado.",
       "Consejos adicionales: No enterrar demasiado el bulbo.",
     ]
   ),
   new Plant(
     24,
     "Milenrama rosa",
     "Variante ornamental de la milenrama, útil en infusiones y para la piel.",
     ["Medicinal", "Decorativa", "Facil"],
     "https://cdn.pixabay.com/photo/2017/07/08/18/18/yarrow-2484642_960_720.jpg",
     "Riego ligero. Tolera sequía.",
     "Sol directo.",
     "Infusión calmante o en cremas caseras.",
     "Cicatrizante, útil para piel inflamada o acné.",
     "Perenne. Requiere poca agua y poda ligera tras floración.",
     [
       "Temporada: Primavera a otoño.",
       "Tiempo hasta recolección: 2-3 años.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego ligero.",
       "Consejos adicionales: Puede necesitar poda tras floración.",
     ]
   ),
   new Plant(
     29,
     "Pimiento",
     "Verdura popular en múltiples platos, desde guisos hasta ensaladas.",
     ["Comestible"],
     "https://cdn.pixabay.com/photo/2016/08/03/01/07/bell-pepper-1568009_960_720.jpg",
     "Riego moderado, constante y sin encharcar.",
     "Sol directo. Necesita calor.",
     "Asado, crudo en ensaladas, relleno o en sofritos.",
     "Fuente de vitamina C y antioxidantes.",
     "Sembrar en primavera en tierra rica y bien drenada. Requiere temperaturas cálidas (mínimo 20 °C). Germina en 7-15 días y se trasplanta cuando tenga 4-6 hojas. Poda ligera para estimular el crecimiento de frutos.",
     [
       "Temporada: Primavera a verano.",
       "Tiempo hasta recolección: 70-90 días.",
       "Suelo/Maceta: Suelo rico y bien drenado.",
       "Regado: Riego moderado.",
       "Consejos adicionales: Asegurar una exposición solar óptima.",
     ]
   ),
   new Plant(
     30,
     "Cebolla",
     "Base de muchos platos. Se puede cultivar incluso en macetas profundas.",
     ["Comestible"],
     "https://cdn.pixabay.com/photo/2016/03/05/19/02/onions-1238332_960_720.jpg",
     "Riego ligero al inicio, luego espaciado.",
     "Sol directo. Le gusta el clima templado.",
     "Cruda en ensaladas, caramelizada, en guisos, caldos y sofritos.",
     "Rica en quercetina y compuestos antioxidantes.",
     "Plantar en surcos separados unos 15 cm. No enterrar demasiado el bulbo. Cosechar cuando las hojas se doblen y amarilleen. Secar bien antes de almacenar. Evitar riego excesivo en la fase final para evitar podredumbre.",
     [
       "Temporada: Primavera a otoño.",
       "Tiempo hasta recolección: 3-4 meses.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego ligero.",
       "Consejos adicionales: Evitar riego excesivo al final del ciclo.",
     ]
   ),
   new Plant(
     32,
     "Zanahoria",
     "Raíz comestible dulce y crujiente. Muy fácil de cultivar.",
     ["Comestible", "Huerto urbano"],
     "https://cdn.pixabay.com/photo/2018/08/08/10/44/carrots-3590733_960_720.jpg",
     "Riego regular y moderado. No encharcar.",
     "Sol directo o semisombra.",
     "En crudo, cocida, en purés o postres.",
     "Rica en betacarotenos, mejora la visión y el sistema inmune.",
     "Tierra suelta, profunda y sin piedras para que la raíz crezca recta. Siembra directa, no trasplante. Mantener húmedo hasta la germinación (7-21 días). Aclareo para dejar espacio entre plantas. Cosechar entre 70 y 100 días.",
     [
       "Temporada: Primavera a otoño.",
       "Tiempo hasta recolección: 2-3 meses.",
       "Suelo/Maceta: Suelo suelto y profundo.",
       "Regado: Riego regular.",
       "Consejos adicionales: Mantener el suelo libre de piedras.",
     ]
   ),
   new Plant(
     33,
     "Rúcula",
     "Hortaliza de hoja con sabor ligeramente picante. Crece rápido y en poco espacio.",
     ["Comestible", "Maceta", "Balcon"],
     "https://cdn.pixabay.com/photo/2017/06/08/10/42/arugula-2385626_960_720.jpg",
     "Riego regular, mantener humedad sin encharcar.",
     "Semisombra o sol suave.",
     "En ensaladas, pizzas, bocadillos o pesto.",
     "Rica en vitamina K, C y compuestos antiinflamatorios.",
     "Ideal para maceta ancha pero poco profunda. Sembrar directamente, germina en pocos días. Puedes cortar hojas jóvenes y seguir cosechando varias semanas. Evita calor extremo que acelera la floración.",
     [
       "Temporada: Primavera a otoño.",
       "Tiempo hasta recolección: 4-6 semanas.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego regular.",
       "Consejos adicionales: Cosecha las hojas cuando estén tiernas.",
     ]
   ),
   new Plant(
     34,
     "Espinaca",
     "Verdura de hoja muy nutritiva. Perfecta para cultivo en espacios reducidos.",
     ["Comestible", "Maceta", "Balcon"],
     "https://cdn.pixabay.com/photo/2017/04/17/10/32/spinach-2238779_960_720.jpg",
     "Riego moderado, suelo siempre ligeramente húmedo.",
     "Semisombra o sol parcial.",
     "Salteada, en ensaladas o batidos verdes.",
     "Alto contenido en hierro, ácido fólico y antioxidantes.",
     "Siembra directa en maceta profunda (mínimo 20 cm). Resiste bien el frío. Cosecha hojas exteriores cuando tengan buen tamaño. Crece rápido y se adapta bien a espacios pequeños si se mantiene húmeda y ventilada.",
     [
       "Temporada: Otoño a primavera.",
       "Tiempo hasta recolección: 1-2 meses.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego moderado.",
       "Consejos adicionales: Ideal para cultivo en climas frescos.",
     ]
   ),
   new Plant(
     35,
     "Lechuga",
     "Clásica verdura de hoja fácil de cultivar incluso en jardineras.",
     ["Comestible", "Maceta", "Balcon"],
     "https://cdn.pixabay.com/photo/2016/06/18/17/42/lettuce-1460606_960_720.jpg",
     "Riego frecuente pero sin encharcar. Evitar sequías.",
     "Sol suave o semisombra.",
     "En ensaladas o como base para wraps y bocadillos.",
     "Rica en agua y fibra, ligera y digestiva.",
     "Ideal en jardineras de 20 cm de profundidad. Siembra directa o trasplante. Puedes recolectar hojas exteriores poco a poco o cortar la planta entera. Mantén el sustrato húmedo y evita el calor excesivo que causa floración prematura.",
     [
       "Temporada: Primavera a otoño.",
       "Tiempo hasta recolección: 1-2 meses.",
       "Suelo/Maceta: Suelo bien drenado.",
       "Regado: Riego frecuente.",
       "Consejos adicionales: Evitar exposición prolongada al sol directo.",
     ]
   ),
   new Plant(
     36,
     "Rábano",
     "Raíz pequeña, de cultivo rápido y perfecta para principiantes.",
     ["Comestible", "Maceta", "Balcon"],
     "https://cdn.pixabay.com/photo/2016/05/04/20/08/radish-1374782_960_720.jpg",
     "Riego constante, suelo húmedo pero no encharcado.",
     "Sol directo o semisombra.",
     "Crudo en ensaladas, encurtido o como snack.",
     "Bajo en calorías, rico en vitamina C y potasio.",
     "Se adapta bien a macetas de al menos 15 cm de profundidad. Siembra directa cada pocas semanas para cosecha continua. Germina en 3-7 días y se cosecha en 25-40 días.",
     [
       "Temporada: Primavera a otoño.",
       "Tiempo hasta recolección: 25-40 días.",
       "Suelo/Maceta: Suelo bien drenado, ligero.",
       "Regado: Riego constante.",
       "Consejos adicionales: Mantener el suelo húmedo, pero evitar el encharcamiento. Ideal para siembra sucesiva.",
     ]
   ),

   new Plant(
     38,
     "Tomate cherry",
     "Variedad compacta de tomate ideal para balcones, muy productiva en maceta.",
     ["Comestible", "Maceta", "Balcón", "Facil"],
     "https://cdn.pixabay.com/photo/2018/06/03/16/51/tomato-3456854_960_720.jpg",
     "Riego abundante y regular. No mojar hojas.",
     "Sol directo mínimo 6h/día.",
     "Crudos en ensaladas, brochetas o salsas frescas.",
     "Fuente de licopeno, antioxidante beneficioso para el corazón.",
     "Maceta profunda (30 cm mínimo). Usa tutor o jaula para sostenerlo. Polinización manual en balcones ayuda a la producción. Requiere abono cada 15 días y buena exposición solar.",
     [
       "Temporada: Primavera a verano.",
       "Tiempo hasta recolección: 60-85 días.",
       "Suelo/Maceta: Suelo bien drenado y fértil.",
       "Regado: Riego regular, evitando mojar las hojas.",
       "Consejos adicionales: Usa un tutor para que las plantas crezcan rectas. Asegura que la planta reciba al menos 6 horas de sol al día.",
     ]
   ),

   new Plant(
     39,
     "Pimiento italiano",
     "Planta compacta y productiva. Muy usada en cocina mediterránea.",
     ["Comestible", "Maceta", "Balcón", "Facil"],
     "https://cdn.pixabay.com/photo/2014/04/10/11/06/chili-320278_960_720.jpg",
     "Riego regular, sin encharcar. Más riego en floración.",
     "Sol directo.",
     "A la plancha, en guisos, rellenos o crudos.",
     "Rico en vitamina C y antioxidantes.",
     "Maceta profunda y amplia. Necesita calor y sol. Usa tutor. Retira las primeras flores para estimular producción. Asegura buen drenaje y riega solo cuando la tierra esté seca en superficie.",
     [
       "Temporada: Primavera a verano.",
       "Tiempo hasta recolección: 70-90 días.",
       "Suelo/Maceta: Suelo bien drenado, fértil.",
       "Regado: Evitar el encharcamiento. Aumentar el riego durante la floración.",
       "Consejos adicionales: El pimiento necesita mucho calor y sol para crecer correctamente. Usa un tutor si es necesario y retira las primeras flores para fomentar más frutos.",
     ]
   ),

   new Plant(
     41,
     "Perejil",
     "Aromática resistente, ideal para jardineras y pequeños espacios.",
     ["Comestible", "Aromática", "Balcón", "Facil"],
     "https://cdn.pixabay.com/photo/2014/04/10/11/06/parsley-320278_960_720.jpg",
     "Riego frecuente y uniforme.",
     "Semisombra o sol parcial.",
     "Como condimento en casi cualquier plato.",
     "Fuente de hierro y vitamina C.",
     "Maceta de al menos 20 cm de profundidad. Siembra directa o trasplante. Cosecha hojas exteriores cuando estén bien formadas. Crece lentamente al principio pero se mantiene varios meses si se cuida.",
     [
       "Temporada: Primavera a otoño.",
       "Tiempo hasta recolección: 60-90 días.",
       "Suelo/Maceta: Suelo ligeramente ácido y bien drenado.",
       "Regado: Riego frecuente, evitando el encharcamiento.",
       "Consejos adicionales: El perejil puede crecer lentamente al principio. Siembra continua para asegurar una cosecha constante.",
     ]
   ),

   new Plant(
     42,
     "Pimiento de Padrón",
     "Variedad gallega de pequeño tamaño, famosa por su sabor suave o picante sorpresa.",
     ["Comestible", "Balcón", "Facil"],
     "https://cdn.pixabay.com/photo/2015/07/02/10/07/pimientos-828888_960_720.jpg",
     "Riego moderado. Más frecuente en floración y fruto.",
     "Sol directo mínimo 6h/día.",
     "Fritos en sartén con sal gruesa. También en tortillas o acompañamientos.",
     "Fuente de antioxidantes y vitaminas A y C. Ayuda a la digestión.",
     "Maceta de al menos 30 cm de profundidad. Prefiere climas cálidos. Necesita tutor si crece mucho. Cosechar verdes y pequeños (5-8 cm). Usar abono orgánico o compost cada 2 semanas. Importante buen drenaje y exposición solar constante.",
     [
       "Temporada: Primavera a verano.",
       "Tiempo hasta recolección: 60-75 días.",
       "Suelo/Maceta: Suelo bien drenado y rico en nutrientes.",
       "Regado: Moderado, más frecuente durante la floración y cuando el fruto aparece.",
       "Consejos adicionales: El pimiento de Padrón se desarrolla bien en climas cálidos. Recuerda cosechar los frutos pequeños para mantener la planta productiva.",
     ]
   ),
 ];

